name: ci
on: [push, pull_request]
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install numpy mypy coverage
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: python run_all.py
